#!/bin/sh

#questions
read -p "Enter your email address (for ssh keygen): " email
read -p "Do you want to deploy my dotfiles [y/n]: " deploydotfiles

# sudo check
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run with sudo" 
   exit 1
fi

# start
echo -ne "
-------------------------------------------------------------------------
			WECLOME
   THIS SCRIPT WILL INSTALL AND CONFIGUREND ALL THE APPLICATIONS I USE
-------------------------------------------------------------------------
"

sleep 3
clear

echo "executing script in 3..."
sleep 1
clear
echo "executing script in 3  2..."
sleep 1
clear
echo "executing script in 3  2  1..."
sleep 1
clear

# package installation tweaks (pacman and makepkg)
echo "MAKING PACMAN FAST,COLORFULL AND MORE READABLE"
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
echo "USING ALL CORES FOR COMPILATION"
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf


# update system
sudo pacman -Syu --noconfirm

#installing packages from pacman
PKGS=(

	'android-tools' #useful programs
	'htop'
	'neovim'
	'mpv'
	'ranger'
	'zsh' 'zsh-syntax-highlighting'
	'partitionmanager'
	'jq'
	'fzf'
	'bluedevel'
	'bluez-utils'
	'git'
	'base-devil'
	'yt-dlp'
	'wget'
	'openssh'

	'plasma' #kde
	'sddm'
	'konsole'

	'gwenview' #kde apps
	'okular'
	'ark'
	'spectacle'

)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm --needed
done


#installing yay
echo "INSTALLING YAY, AN AUR HELPER"
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -frsi
cd ~

#installing packages from aur
echo "INSTALLING PACKAGES FROM THE AUR"
PKGS=(

	'auto-cpufreq'
	'librewolf-bin'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    yay -S "$PKG" --removemake
done

#enable/disable systemctl services
sudo systemctl enable bluetooth
sudo systemctl enable auto-cpufreq.service
sudo systemctl enable sddm


echo "Disablingg Baloo"
balooctl suspend
balooctl disable
rm -rf ~/.local/share/baloo


#deploying dotfiles

if [[ deploydotfiles = "y" ]]
then
    echo "CLONING MY DOTFILES FROM GITHUB"
    git clone https://github.com/saqibmir1/dotfiles.git

    #home folder
    mv -f ~/dotfiles/.zshrc ~
    mv -f ~/dotfiles/.zprofile ~
    #mv -f ~/dotfiles/.gitconfig ~
    mv -f ~/dotfiles/kde_shortcuts.kksrc ~/.config

    #.local/bin folder
    mkdir -p ~/.local/bin
    mv ~/dotfiles/.local/bin/* ~/.local/bin

    # .config folder
    mkdir ~/.config/shell
    mv -f ~/dotfiles/.config/shell/aliasrc ~/.config/shell/


    #.local/share folder
    mkdir -p ~/.local/share/wall
    mv -f ~/dotfiles/.local/share/wall/* ~/.local/share/wall
fi

#change shell to zsh
echo "CHANGING SHELL TO ZSH"
chsh -s $(which zsh)
mkdir -p ~/.cache/zsh

#make new home dirs
mkdir Code gitPackages Code Projects

#cleaning
echo "CLEANING HOME DIRECTORY"
rm ~/.bash*
#rm -rf ~/dotfiles
rm -rf ~/yay-bin
rm -rf ~/auto-arch
rmdir Templates Public
sudo pacman -Rns discover --noconfirm


#generating ssh key for github
if [[ "$deploydotfiles" = "y" ]]; then
	#generating ssh key for github
	echo "GENERATING SSH KEY FOR GITHUB"
	ssh-keygen -t ed25519 -C "$email"
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/id_ed25519
	echo "KEY GENERATED"
fi

# reboot
echo "All done, Reboot your system now"
